"""
Pentagonal numbers are generated by the formula,
Pn=n(3n-1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
for which their sum and difference are pentagonal
and D = |Pk - Pj| is minimised; what is the value of D?
"""
import time

t1 = time.clock()
penta_set = set()


def pentagonal(n):
    return n * (3 * n - 1)//2


for n in range(1, 2400):
    penta_set.add(pentagonal(n))

for pj in penta_set:
    for pk in penta_set:
        if pk - pj  in penta_set and pj + pk in penta_set:
            print(pk-pj)

print(time.clock() - t1, "seconds")
